DROP table IF EXISTS `TO_DO_LIST` CASCADE;
DROP table IF EXISTS `ITEM` CASCADE;

CREATE table IF NOT EXISTS `TO_DO_LIST` (
	`id` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`complete` BIT NOT NULL
);

CREATE table IF NOT EXISTS `ITEM` (
	`id` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`complete` BIT NOT NULL,
	`TO_DO_LIST_ID` INT(11)
);